const mockEvents = {
  "city": {
    "id": 1007700,
    "city": "München",
    "lat": 48.14,
    "lon": 11.58,
    "state": "",
    "country": "de",
    "zip": "meetup3",
    "member_count": 1257
  },
  "events": [
    {
      "created": 1594127800000,
      "duration": 14400000,
      "fee": {
        "accepts": "cash",
        "amount": 40,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "271771314",
      "name": "ImprovSTAR is proud to host Noah Levin in Munich with his workshop PAY ATTENTION",
      "rsvp_limit": 16,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598461200000,
      "local_date": "2020-08-26",
      "local_time": "19:00",
      "updated": 1597095762000,
      "utc_offset": 7200000,
      "waitlist_count": 2,
      "yes_rsvp_count": 16,
      "venue": {
        "id": 26760672,
        "name": "Landsberger Str. 521",
        "lat": 48.146484375,
        "lon": 11.460190773010254,
        "repinned": true,
        "address_1": "Landsberger Str. 521",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1579537687000,
        "name": "ImprovSTAR English Intermediate Improv Theater Group",
        "id": 33224143,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "ImprovSTAR",
        "who": "improvisers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/ImprovSTAR/events/271771314/",
      "description": "<p>Workshop PAY ATTENTION!</p> <p>Use callbacks, reincorporation, and using patterns to be brilliant. When an audience member “gets it,” it is a cathartic moment, a surprise, a relief, a laugh. Recognition of a pattern is hard-wired into our human brains and we can use it on stage. Learn techniques to make patterns and use callbacks, tickle those hard to reach right frontal lobes and delight your audiences.<br/>Minimum Level: General<br/>Max Sts: 16</p> <p>Noah Levin hails from Ketchum, Idaho, USA and grew up performing theatre in schools and summer camps until earning a degree in Theatre and Education from the University of California in San Diego. Noah taught and performed improv, theatre and stand up comedy, and received formal improv training, at the famous PIT and UCB theatres in New York. Living in Barcelona since 2011, Noah has rapidly expanded his interests performing, teaching, and organizing BIG (Barcelona Improv Festival) as well as the European improv collective Ohana. He also acts in plays, produces live comedy shows, hosts a weekly radio show (Nick and Noah Need Help), and travels around Europe teaching and performing improv.</p> <p>For more info visit",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1597310937000,
      "duration": 10800000,
      "id": "hmdpwrybclbhc",
      "name": "Massage with Robin's Hands",
      "rsvp_limit": 6,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598371200000,
      "local_date": "2020-08-25",
      "local_time": "18:00",
      "updated": 1597749113000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26389892,
        "name": "Königsplatz",
        "lat": 48.14606475830078,
        "lon": 11.564334869384766,
        "repinned": false,
        "address_1": "Königsplatz 1",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1597153092000,
        "name": "Munich Labyrynsel",
        "id": 34082878,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munich-Labyrynsel",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munich-Labyrynsel/events/hmdpwrybclbhc/",
      "description": "<p>We go, meditate together and take our time.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1595333312000,
      "duration": 9000000,
      "id": "272058870",
      "name": "DATAMADNESS MUNICH #1",
      "rsvp_limit": 50,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1600360200000,
      "local_date": "2020-09-17",
      "local_time": "18:30",
      "updated": 1597311924000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 22,
      "venue": {
        "id": 26968018,
        "name": "Sendlinger Str. 7",
        "lat": 48.13581085205078,
        "lon": 11.572131156921387,
        "repinned": true,
        "address_1": "Sendlinger Str. 7",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1594983403000,
        "name": "DATAMADNESS MUNICH",
        "id": 33975811,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "datamadness-munich",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/datamadness-munich/events/272058870/",
      "description": "<p>topics: data science, product management, r, dashboards</p> <p># DATAMADNESS MUNICH #1 (September)</p> <p>* The Power of Data Product Management (Robert Keil)<br/>* Data Science MVPs with R Shiny (Sarah Stemmler)</p> <p>This event will be in English.</p> <p>Space is limited, please do register for a free ticket.</p> <p>We look forward to seeing you!</p> <p>## Health &amp; Safety Guidelines</p> <p>We hope to make this an offline event but amidst the current development of the pandemic, we really depend on your support. We will share the health and safety guidelines for our event here soon and expect all attendees to follow the instructions. Thanks for your cooperation!</p> <p>## Agenda</p> <p>18:00 – Doors open.</p> <p>18:30 – Welcome.</p> <p>18:45 – The Power of Data Product Management.</p> <p>19:30 – Break with pizza and cold drinks.</p> <p>20:00 – Data Science MVPs with R Shiny.</p> <p>20:45 – Open mic.</p> <p>21:00 – End.</p> <p>## Location</p> <p>The event will take place at the Usercentrics office in the heart of Munich. We will put up signs so you can't miss us.</p> <p>## Open mic</p> <p>The end of the event is dedicated to our attendees who want to share something they care about with the community. Any content is welcome, as long as it fits in three minutes and does not advertise paid products or services. If you want to reserve a spot, please reach out.</p> <p>## Acknowledgement</p> <p>Thanks a lot to our speakers Robert and Sarah!</p> <p>Also a big thank you to our sponsors:</p> <p>* Instaffo, for supporting the organization.<br/>* Usercentrics, for hosting the event.</p> <p>## Contact</p> <p>If you have any questions or suggestions, please feel free to contact us via:</p> <p>* Meetup<br/>* Telegram: <a href=",
      "visibility": "public",
      "pro_is_email_shared": false,
      "member_pay_fee": false
    },
    {
      "created": 1580900882000,
      "duration": 10800000,
      "id": "txxrnrybcmbkb",
      "name": "IOTA München Stammtisch",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1599498000000,
      "local_date": "2020-09-07",
      "local_time": "19:00",
      "updated": 1580900882000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 5,
      "venue": {
        "id": 26223377,
        "name": "Gasthaus Alter Wirt",
        "lat": 48.100467681884766,
        "lon": 11.544821739196777,
        "repinned": false,
        "address_1": "Fraunbergstraße 8",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1522790396000,
        "name": "IOTA Meetup München",
        "id": 28040988,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "IOTA-Muc",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/IOTA-Muc/events/txxrnrybcmbkb/",
      "description": "<p>Der nächste offizielle IOTA München Stammtisch findet immer am 1. Montag des Monats um 19:00Uhr im Alten Wirt Thalkirchen statt!</p> <p>Der IOTA München Stammtisch wurde ins Leben gerufen, damit die Münchner Community sich regelmäßig treffen kann, um über aktuelle Entwicklungen zu diskutieren. Schaut einfach mal vorbei!</p> ",
      "how_to_find_us": "Gleich neben U3 Thalkirchen",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1591348394000,
      "duration": 385200000,
      "id": "271099242",
      "name": "International JavaScript Conference Munich 2020 - The Hybrid Conference",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1603695600000,
      "local_date": "2020-10-26",
      "local_time": "08:00",
      "updated": 1597742159000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 13,
      "venue": {
        "id": 26495814,
        "name": "Holiday Inn München - Stadtzentrum",
        "lat": 48.13063049316406,
        "lon": 11.589532852172852,
        "repinned": true,
        "address_1": "Hochstraße 3",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1497515784000,
        "name": "International JavaScript Conference",
        "id": 24474394,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "International-JavaScript-Conference",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/International-JavaScript-Conference/events/271099242/",
      "description": "<p>Every year in October, International JavaScript Conference Munich is where seasoned experts get together to discuss methods, libraries, services, models and algorithms to use. Keeping the current situation in mind, we announce that iJS Munich 2020 will be a Hybrid Conference - attend the conference on site or remotely from your home or office.</p> <p>We are looking forward to meeting you this year as well!</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1562750055000,
      "duration": 10800000,
      "id": "tkqsdrybcmbmb",
      "name": "Designer-Stammtisch",
      "rsvp_limit": 35,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1599670800000,
      "local_date": "2020-09-09",
      "local_time": "19:00",
      "updated": 1562750055000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "venue": {
        "id": 26506448,
        "name": "Cafe Zeitgeist",
        "lat": 48.15114212036133,
        "lon": 11.576687812805176,
        "repinned": false,
        "address_1": "Türkenstraße 74",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1444668795000,
        "name": "Münchner Designer-Stammtisch",
        "id": 19020346,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Designer-Stammtisch",
        "who": "Designer",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Designer-Stammtisch/events/tkqsdrybcmbmb/",
      "description": "<p>Liebe DesignerInnen,</p> <p>wir treffen uns jeden 2. Mittwoch im Monat um 19:00 Uhr in (neu:) Zeitgeist in der Türkenstraße.</p> <p>Bringt eure Erfolge, neusten Projekte oder auch kleinen Problemchen mit und teilt sie mit anderen Designern bei einem entspannten Abendessen.</p> <p>Wir freuen uns auf neue Designer und alte Bekannte, und auf einen gemütlichen Abend mit Designer-Kaltsch-und-Tratsch.</p> <p>Lieben Gruß, Ben</p> <p>ps: für alle die gerne länger unterwegs sind finden wir auch diesmal bestimmt wieder eine Location.</p> <p>pps: We mostly chat in German, but English will work just find as well.</p> ",
      "how_to_find_us": "Fragt nach dem Designerstammtisch dort! *** Please ask for the Designerstammtisch there!",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1596579119000,
      "duration": 7200000,
      "fee": {
        "accepts": "cash",
        "amount": 20,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "272365756",
      "name": "ImprovSTAR hosts Budapest Star, Andrew Hefler with his Workshop: „Gotta have it“",
      "rsvp_limit": 14,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598288400000,
      "local_date": "2020-08-24",
      "local_time": "19:00",
      "updated": 1597095748000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 12,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1579537687000,
        "name": "ImprovSTAR English Intermediate Improv Theater Group",
        "id": 33224143,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "ImprovSTAR",
        "who": "improvisers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/ImprovSTAR/events/272365756/",
      "description": "<p>Workshop: „Gotta have it“- Emotions</p> <p>Attitudes, wants and emotional drive. Asking how am I and what do I want? Working with objectives, emotions and attitudes in relationships and scenework. Getting truthful behaviour out of scenes that wants to achieve it's objective while emphasizing emotion, silence and focus over verbal cues. Accessing skills for micro-listening to strengthen the idea that it is not what you say in a scene, but what you hear and see and how that makes you feel that is most playable. This allows us to project and reveal more layers.</p> <p>Andrew Hefler is a performer, director, trainer working in theatre, music, film and television for nearly thirty years. He was first introduced to Improvisational theatre at the age of 10 in grade school in Los Angeles. Since then he has worked with theatre groups in the US, Canada, Europe and since 1994 in his homebase of Budapest. He was a founding member of the experimental impro trio Scalabouche and later he founded Grund Theatre in 2008 developing a company and training methods for actors and shows for performance. He has written and produced TV for comedy Central and AMC. He is an actor at the National Theatre of Hungary and has taught impro at three Universities.</p> <p>ImprovSTAR is absolutely thrilled to have won Andrew for our SUMMER SPECIAL- LINE UP, Online on the 24th August!</p> <p>As we know that many of you haven't had the chance to visit International Improv festivals before, we decided to bring international Stars to you, so you get the best experiences of Improv! Don't miss this chance and book now- you won't regret it!</p> <p>SUMMER SPECIAL WORKSHOP PRICES:<br/>(There are limited spaces so be quick)!</p> <p>We offer you this exceptional price of €60, - for all 4 Workshops, staring:</p> <p>-10th Aug. Philip Geurin from Seattle (\"Improv like Olaf„ Fun …AND)< br /> -17th Aug.Jeromaia Detto from Sydney(\"Engage the Stage„- Object work/Mime)<br/>-24th Aug. Andrew Hefler from Budapest („Gotta have it“-Emotions)<br/>-31st Aug. Aree Witoelar from Oslo („The Game“- Game of the scene)</p> <p>Or €20, - per individual workshop.<br/>For the Summer Special events, we only accept PayPal or bank transfer before the event to secure the booking. Please transfer the booking fee to:<br/>Bank account: Name: Kyra Thaysen und Georgi Chulkov<br/>IBAN: DE[masked]<br/>BIC/SWIFT: COBADEFFXXXDE[masked]</p> <p>Or Via PayPal: [masked]</p> <p>Please only RSVP if you will be attending this workshop 100% for certain, and pay before in advance to save your spot.<br/>Please understand that you may only attend this workshop if you have successfully registered for the event on Meetup and have paid.</p> <p>What is our purchasing, cancellation, and refund policy?</p> <p>If you have already registered for workshop/s, and you are no longer able to attend, our cancellation policy is as follows:<br/>• You will get a full refund only if YOU are able to replace your position with another participant. Otherwise you will get NO refund.<br/>• Sorry, no refund if: You don't show up and don't change your RSVP on Meetup.</p> <p>Other cancellations and schedule changes<br/>It's unlikely to happen, but we reserve the right to cancel or reschedule an event due to the spread of COVID-19, sudden low enrolment, presenter illness, or other circumstances. If the event is cancelled, participants will receive a full refund of their registration fee. If the event is rescheduled, participants will have the option of attending the rescheduled event or receiving a full refund.</p> <p>Location: Zoom - Link will be sent to you once you have signed up and payed.</p> <p>All workshops are held in English.</p> <p>Looking forward to you!</p> ",
      "visibility": "public",
      "member_pay_fee": false,
    },
    {
      "created": 1594142093000,
      "duration": 7200000,
      "id": "271775637",
      "name": "Beer, Brotzeit and IoT @ Concept Reply",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1603384200000,
      "local_date": "2020-10-22",
      "local_time": "18:30",
      "updated": 1598025454000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 36,
      "venue": {
        "id": 26066109,
        "name": "Luise-Ullrich-Straße 14",
        "lat": 48.14474868774414,
        "lon": 11.538175582885742,
        "repinned": true,
        "address_1": "Luise-Ullrich-Straße 14",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1508251656000,
        "name": "München IoT Meetup",
        "id": 26294946,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Muenchen-IoT-Meetup",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Muenchen-IoT-Meetup/events/271775637/",
      "description": "<p>We will also broadcast the event live for people who would rather stay at home on YouTube: <a href=\"https://youtu.be/JYnYmkfO4PU\" class=\"embedded\">https://youtu.be/JYnYmkfO4PU</a></p> <p>How to find the new venue:<br/>Enter the Nove Building from Luise-Ullrich-Straße 14 (you should see a statue and a restaurant outside). On entering you will see the main reception in front of you with a security guard, two lifts to the left and a model of the building to the right. Walk toward the reception, take the first left and walk toward the other two lifts in front of you. The first door on the left with the Reply logo leads to the Meetup on the *ground floor*.</p> <p>Agenda:</p> <p>18:30: Brotzeit<br/>19:00: Markus Jung (OSRAM) - The OSRAM portfolio of IoT connected products<br/>19:30: Christopher Ziegler (Actyx.io) - The modern way of automating and digitizing factories<br/>20:00: Networking</p> <p>Food and drink served throughout. All presentations in English.</p> ",
      "how_to_find_us": "Public transport",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581340324000,
      "duration": 32400000,
      "id": "268602441",
      "name": "Hack&Jump - München 2020",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1604574000000,
      "local_date": "2020-11-05",
      "local_time": "12:00",
      "updated": 1581340324000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 6,
      "venue": {
        "id": 26120186,
        "name": "HANS IM GLÜCK Burgergrill & Bar",
        "lat": 48.120391845703125,
        "lon": 11.602923393249512,
        "repinned": true,
        "address_1": "St.-Martin-Straße 57",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1501244830000,
        "name": "Tech_Hub München",
        "id": 25186228,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Tech_Hub-Munchen",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Tech_Hub-Munchen/events/268602441/",
      "description": "<p>Join our IT-Job-Shuttle to the digital economy of Munich. During the tour, you can look behind the scenes of high-tech companies and have valuable contacts to IT-professionals of the participating companies. Catering will be provided all day. To the end of the day we have a Get-Together and serve good food and free beer.</p> <p>Steig ein in den IT-Job-Shuttle durch die Münchner Digitalwirtschaft. Während der mehrstündigen Tour kannst Du hinter die Kulissen von Hightech-Unternehmen schauen und wertvolle Kontakte zu Fachleuten und Personalern in den beteiligten Unternehmen knüpfen. Für die Verpflegung zwischendurch ist bestens gesorgt. Zum Ausklang des Abends erwarten Dich dann nochmal gutes Essen und Freibier.</p> <p>#hightech #kaffeefahrt #ITjobs</p> <p>Please REGISTER HERE",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581639725000,
      "duration": 10800000,
      "id": "268694958",
      "name": "Unternehmertreffen & Start up-Event in München",
      "rsvp_limit": 30,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601827200000,
      "local_date": "2020-10-04",
      "local_time": "18:00",
      "updated": 1581946161000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 15,
      "venue": {
        "id": 26865368,
        "name": "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        "lat": 48.128822326660156,
        "lon": 11.574684143066406,
        "repinned": false,
        "address_1": "Frauenhoferstraße 32, 80469 München",
        "city": "München",
        "country": "DE",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1581635431000,
        "name": "Unternehmertreffen and Start up-Event München",
        "id": 33341612,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Unternehmertreffen-Start-up-Event-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694958/",
      "description": "<p>DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT</p> <p>INVESTOREN / BUSINESS-ANGEL*<br/>*mehr Details in der Beschreibung</p> <p>Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an.</p> <p>Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken!</p> <p>Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN.</p> <p>Informationen und Tickets finden sich unter: <a href=\"https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3\" class=\"linkified\">https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3</a></p> <p>Gerne auch per Telefon: Christian Lenk +49 (0)[masked]</p> <p>Ablauf:<br/>Begrüßung<br/>Kurze Vorstellungsrunde:<br/>- Name, Alter, Herkunft<br/>- Aktuelle Geschäftsbereiche und Projekte</p> <p>Anschließend dürfen 2 freiwillige Unternehmer ihre Geschäfte/ Projekte der Gruppe vorstellen, jeweils circa 15 Minuten.</p> <p>Nach jeder Runde wird eine Unterstützerrunde (Nutzung der Schwarmintelligenz) eingeleitet, wo die Anwesenden für das vorgestellte Projekt zB.:<br/>- Helfende Kontakte zusprechen können<br/>- Ideen zur Förderung des Geschäfts einbringen dürfen<br/>- Selbst Interesse äußern können, um neue Geschäftsbeziehungen anzubahnen.</p> <p>Wenn du einen interessanten Partner kennengelernt hast, könnt ihr eure Visitenkarten austauschen. Diese Runde ist ebenfalls mit 15 Minuten angesetzt.</p> <p>Abschließend wird das Treffen mit einem Referenten aus dem Forex Markt oder Krypto Bereich abgerundet und offen ausgetauscht.</p> <p>Dein Mehrwert<br/>Du lernst jeden Teilnehmer persönlich kennen, wodurch dein Netzwerk sehr schnell wächst. Durch neue Geschäftskontakte und den sich daraus ergebenden Möglichkeiten, kannst du große Umsatzsteigerungen erzielen. Du lernst regionale Geschäftspartner kennen, die, wie auch du, etwas erreichen und schaffen wollen. Gemeinsam könnt ihr eure Ideen schneller und einfacher umsetzen.</p> <p>Informelle Gespräche<br/>Nach dem offiziellen Teil des Unternehmertreffens, in dessen Mittelpunkt die Nutzung der Schwarmintelligenz für die vorgestellten Projekte steht, geht es mit lockerem Netzwerken und viel informellem Austausch weiter. So entstehen echte Geschäftsfreundschaften.</p> <p>Netzwerken<br/>Netzwerke bilden heute die Basis für viele unternehmerische Aktivitäten. Genau dies ist der Grundgedanke von Munich-Milan Wir machen miteinander Geschäfte, unterstützen uns gegenseitig – und haben auch eine Menge Spaß.</p> <p>Melde dich jetzt für Sonntag an und wir sehen uns beim Unternehmertreffen!<br/>Anmelden ist Pflicht: Nach vielen Nachfragen noch der Gästelistelink:<br/><a href=\"https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3\" class=\"linkified\">https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3</a></p> <p>Nur wer die Reservierung für 20,00 Euro bestätigt kann kommen.</p>",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1596925483000,
      "duration": 12600000,
      "fee": {
        "accepts": "paypal",
        "amount": 98,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": true
      },
      "id": "272453545",
      "name": "*Build & Taste* - Weinregal-Bau und Wein-Tasting",
      "rsvp_limit": 7,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598713200000,
      "local_date": "2020-08-29",
      "local_time": "17:00",
      "updated": 1597696335000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26892087,
        "name": "Zero Dosage",
        "lat": 48.14724349975586,
        "lon": 11.56142520904541,
        "repinned": true,
        "address_1": "Augustenstraße 25",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1571323841000,
        "name": "Holzköpfchen - Möbel & Deko selbstgemacht (DiY)",
        "id": 32903650,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Holzkoepfchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Holzkoepfchen/events/272453545/",
      "description": "<p>Bei diesem besonderen Event bauen wir Dein eigenes Weinregal und verkosten fünf charaktervolle und spannende Naturweine. Gemeinsam mit netten Leuten und in entspannter Atmosphäre werdet ihr handwerklich kreativ und entdeckt ungeahnte Geschmäcker atypischer Weinstile.</p> <p>Was erwartet Euch:</p> <p>Teil 1: Wir bauen Euer Weinregal und werden handwerklich kreativ: mit Holz, Kupfer, Metall und Filz werden wir schleifen, schneiden, lochen, schrauben, ölen uvm. Nebenbei lernt Ihr etwas über unsere heimischen Hölzer und deren Verarbeitung. Weitere Informationen zu unseren Weinregalen findet Ihr unter holzkoepfchen.de.</p> <p>Teil 2: Verkostung von spannenden &amp; charaktervollen Naturweinen. Hier lernt Ihr spannende Details zu Naturweinen, ihrer Philosophie sowie deren Herstellung. Wir degustieren eine Reihe einzigartiger Naturweine, von Weiß-, Rot- über Rosé- bis hin zu Orange-Weinen. Ob trüb oder ungeschwefelt, es erwarten Euch eigenwillige Weinstile, die Euch mit neuartigen Geschmackserlebnissen überraschen werden.</p> <p>Das Event, inkl. Verkostung von fünf Naturweinen und Weinregal-Bau kostet wie folgt:<br/>98,00 € Weinregal Volando<br/>108,00 € Weinregal Dado<br/>176,00 € Weinregal Bodeguita</p> <p>Anmeldung im Laden oder online unter: www.holzkoepfchen.de/kurse</p> <p>Material und Werkzeug sind inklusive. Es sind keine Vorkenntnisse für den Baukurs notwendig. Die Teilnehmerzahl ist auf 7 Personen limitiert.</p> <p>Wir freuen uns auf Euch-<br/>Max von Zero Dosage &amp;<br/>Tom von Holzköpfchen</p> ",
      "how_to_find_us": "Das Weinlokal Zero Dosage findest du in der Augustenstraße 25, der Münchner Maxvorstadt.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1579163487000,
      "duration": 7200000,
      "fee": {
        "accepts": "cash",
        "amount": 42,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "267957933",
      "name": "Agile Lean Munich 2020 – Der zweite ganztägige Open Space in München",
      "rsvp_limit": 80,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1605340800000,
      "local_date": "2020-11-14",
      "local_time": "09:00",
      "rsvp_close_offset": "PT24H",
      "updated": 1588596438000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 39,
      "venue": {
        "id": 26082467,
        "name": "codecentric AG",
        "lat": 48.12557601928711,
        "lon": 11.610230445861816,
        "repinned": true,
        "address_1": "August-Everding-Straße 20",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1552484914000,
        "name": "Agile Lean Munich",
        "id": 31379982,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Agile-Lean-Munich",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Agile-Lean-Munich/events/267957933/",
      "description": "<p>Der neue Termin für die ALM steht: 14. November 2020!</p> <p>Liebe Teilnehmenden und Interessierten der #agilen Community,<br/>nach Absprache mit @codecentric München, als Veranstaltungs-Ort-Geber haben wir einen neuen Termin für die zweite ALM am 14.November 2020 gefunden. Auch wenn es bis heute keine Planungssicherheit für die zweite Jahreshälfte gibt, hoffen wir, dass die Situation im November soweit stabil ist, dass wir die ALM guten Gewissens stattfinden lassen können.</p> <p>Die bisher gekauften Tickets behalten natürlich weiter ihre Gültigkeit.</p> <p>Wir hoffen auf eine stabile Situation bis November und freuen uns trotz aller Unsicherheiten auf einen tollen Tag mit Euch!</p> <p>Bleibt weiterhin gesund. Wir sehen uns (hoffentlich) im November!</p> <p>Euer ALM Orga-Team</p> <p>#almnov20 #almmai20 #scrum #kanban</p> <p>--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p> <p>⭐️Dieses Event ist kostenpflichtig (42€ p.P). Tickets erhaltet ihr über unsere Website www.agile-lean-munich.de ⭐️</p> <p>Wir wollen mit euch gemeinsam Themen rund um die agile Organisationsentwicklung besprechen.</p> <p>Agil ist längst nicht nur in der Softwareentwicklung das Mittel der Wahl, um Projekte für alle Beteiligten erfolgreicher durchzuführen. Agile ist eine neue Art zu arbeiten, die Transparenz, Selbstorganisation und Geschäftswert in den Vordergrund stellt und Teams und Unternehmen den Spaß an erfolgreicher Arbeit zurückgibt.</p> <p>Es geht um die Themen, die euch bewegen und die Erfahrungen, die ihr gemacht habt.</p> <p>Für die komplette Verpflegung des Tages (vom Frühstück über das Mittagessen bis zum Abschlussbier) wird gesorgt werden.</p> <p>Wir starten um 8:30 Uhr mit einem Frühstück und der Möglichkeit zum Netzwerken. Der Open Space beginnt um 09:30.</p> <p>Wir wünschen allen Teilnehmern viel Spaß!</p> ",
      "how_to_find_us": "Die Veranstaltung findet in den Räumen der codecentric AG statt",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1585297132000,
      "duration": 7200000,
      "id": "269686692",
      "name": "Pitch Club Developer Edition #63",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602698400000,
      "local_date": "2020-10-14",
      "local_time": "20:00",
      "updated": 1585297132000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "venue": {
        "id": 25959917,
        "name": "Bar Ludwig II",
        "lat": 48.12186813354492,
        "lon": 11.58230972290039,
        "repinned": false,
        "address_1": "Hochstraße 77",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1539021073000,
        "name": "Pitch Club Developer Edition München",
        "id": 30141555,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Pitch-Club-Developer-Edition-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/269686692/",
      "description": "<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 14. Oktober 2020 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #63” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "local_time": "19:00",
      "local_date": "2020-08-25",
      "link": "https://www.meetup.com/rice-cookie-improv/events/fzvpwrybclbhc/",
      "visibility": "public_limited",
      "group": {
        "created": 1468649601000,
        "name": "Rice Cookie Improvtheater in Munich",
        "id": 20189476,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "rice-cookie-improv",
        "who": "Improv-Enthusiasts",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "waitlist_count": 0,
      "yes_rsvp_count": 8,
      "duration": 7200000,
      "time": 1598374800000,
      "utc_offset": 7200000,
      "name": "Get Loose with Improv",
      "id": "fzvpwrybclbhc"
    },
    {
      "created": 1578988979000,
      "duration": 10800000,
      "id": "267900623",
      "name": "München OutSystems Meetup - Save the date!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1605114000000,
      "local_date": "2020-11-11",
      "local_time": "18:00",
      "updated": 1578988979000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "is_online_event": false,
      "group": {
        "created": 1560928375000,
        "name": "Offizielle OutSystems München Meetup Gruppe",
        "id": 32208133,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munchen-OutSystems-Community",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munchen-OutSystems-Community/events/267900623/",
      "description": "<p>Mehr Information wird in Kürze veröffentlicht.</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1594126983000,
      "duration": 14400000,
      "fee": {
        "accepts": "cash",
        "amount": 40,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "271771147",
      "name": "ImprovSTAR is proud to host Noah Levin in Munich with his workshop GET IN TOUCH!",
      "rsvp_limit": 16,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598547600000,
      "local_date": "2020-08-27",
      "local_time": "19:00",
      "updated": 1597095807000,
      "utc_offset": 7200000,
      "waitlist_count": 2,
      "yes_rsvp_count": 16,
      "venue": {
        "id": 26760672,
        "name": "Landsberger Str. 521",
        "lat": 48.146484375,
        "lon": 11.460190773010254,
        "repinned": true,
        "address_1": "Landsberger Str. 521",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1579537687000,
        "name": "ImprovSTAR English Intermediate Improv Theater Group",
        "id": 33224143,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "ImprovSTAR",
        "who": "improvisers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/ImprovSTAR/events/271771147/",
      "description": "<p>Newest workshop: GET IN TOUCH!</p> <p>Do we pay attention to touch? Is bodily sensation a part of your improv or are you just a talking head? In this workshop, we will get in touch with our bodies, get in touch with our partners, and add a new layer to our Improvisation.<br/>Learn how to:<br/>Allow physical touch to resonate in your own body<br/>Let touch affect you and your character<br/>Expand your awareness of touch and physical proximity</p> <p>Min Level: Intermediate/Advanced<br/>Max Sts: 16</p> <p>Noah Levin hails from Ketchum, Idaho, USA and grew up performing theatre in schools and summer camps until earning a degree in Theatre and Education from the University of California in San Diego. Noah taught and performed improv, theatre and stand up comedy, and received formal improv training, at the famous PIT and UCB theatres in New York. Living in Barcelona since 2011, Noah has rapidly expanded his interests performing, teaching, and organizing BIG (Barcelona Improv Festival) as well as the European improv collective Ohana. He also acts in plays, produces live comedy shows, hosts a weekly radio show (Nick and Noah Need Help), and travels around Europe teaching and performing improv.</p> <p>For more info visit",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1582728126000,
      "duration": 10800000,
      "id": "269005331",
      "name": "2. Meetup of Munich Startup Ecosystem. Fundraising",
      "rsvp_limit": 100,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1600360200000,
      "local_date": "2020-09-17",
      "local_time": "18:30",
      "updated": 1589881381000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 63,
      "venue": {
        "id": 26052175,
        "name": "Wayra Germany GmbH",
        "lat": 48.13779830932617,
        "lon": 11.571670532226562,
        "repinned": true,
        "address_1": "Kaufingerstraße 15",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1572942642000,
        "name": "Munich Startup Ecosystem Meetup",
        "id": 32978870,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "startups-munich",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/startups-munich/events/269005331/",
      "description": "<p>As you know Munich has become a vibrant startup hub with a lot of different players. So we decided it is time to build a meetup that brings together all Munich startup ecosystem players, entrepreneurs, investors, policymakers, education leaders, corporates and other stakeholders in one place once every 6 weeks for knowledge exchange, meaningful connections, networking, and recent community updates.</p> <p>How the meetup will look like:</p> <p>We start with Munich ecosystem news, like exits, exciting research, innovative breakthrough, investment rounds, impactful ideas and actions (around 20 min)</p> <p>The newsstand is followed by 3 startup pitches from local startups (3 min each pitch). Everybody is welcome to apply for the pitch spot, even if you have only an idea.</p> <p>We continue our evening with the speaker discussion about the meetup topic (around 30 min)</p> <p>As a closing remark, we will have an open mic for community members questions and “asks” and will help the presenter to get matched with relevant people to answer their questions (15 min)</p> <p>…… and then favorite networking with some healthy and not that healthy drinks!</p> <p>The topic for the second meetup: #fundraising.</p> <p>Learn from the best, build new and strong collaborations and become an active part of your city’s ecosystem! This event is absolutely for everybody who would like to be involved in the startup community development.</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1596706788000,
      "duration": 7200000,
      "id": "272397698",
      "name": "(Un-)Glaubliches München - kuriose Stadtführung",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1600009200000,
      "local_date": "2020-09-13",
      "local_time": "17:00",
      "updated": 1596706845000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "is_online_event": false,
      "group": {
        "created": 1583910278000,
        "name": "Die München Entdecker",
        "id": 33538673,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Lebenszeit-Events",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Lebenszeit-Events/events/272397698/",
      "description": "<p>Klassische Stadtführung? Sicher nicht!</p> <p>Auf dieser Tour hörst du unglaubliche, unbekannte, kuriose, spektakuläre und witzige Geschichten über München. Der Clou dabei ist: ein Teil der Geschichten ist wahr, ein Teil nicht. Beim Miträtseln direkt an den Schauplätzen lernt man die Stadt von einer ganz neuen Seite kennen, die selbst eingefleischte Münchner zum Staunen bringt!</p> <p>Dauer der Tour sind 2 – 2,5 Stunden, inklusive mehreren Überraschungen und einem Getränk.</p> <p>Treffpunkt: am Isartor vor dem Karl Valentin Musäum</p> <p>Ende: Nähe Odeonsplatz</p> <p>Preis 34€</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1596706804000,
      "duration": 7200000,
      "id": "272397699",
      "name": "(Un-)Glaubliches München - kuriose Stadtführung",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1600880400000,
      "local_date": "2020-09-23",
      "local_time": "19:00",
      "updated": 1596706804000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "is_online_event": false,
      "group": {
        "created": 1583910278000,
        "name": "Die München Entdecker",
        "id": 33538673,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Lebenszeit-Events",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Lebenszeit-Events/events/272397699/",
      "description": "<p>Klassische Stadtführung? Sicher nicht!</p> <p>Auf dieser Tour hörst du unglaubliche, unbekannte, kuriose, spektakuläre und witzige Geschichten über München. Der Clou dabei ist: ein Teil der Geschichten ist wahr, ein Teil nicht. Beim Miträtseln direkt an den Schauplätzen lernt man die Stadt von einer ganz neuen Seite kennen, die selbst eingefleischte Münchner zum Staunen bringt!</p> <p>Dauer der Tour sind 2 – 2,5 Stunden, inklusive mehreren Überraschungen und einem Getränk.</p> <p>Treffpunkt: am Isartor vor dem Karl Valentin Musäum</p> <p>Ende: Nähe Odeonsplatz</p> <p>Preis 34€</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1597310937000,
      "duration": 10800000,
      "id": "hmdpwrybcmbcb",
      "name": "Massage with Robin's Hands",
      "rsvp_limit": 6,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1598976000000,
      "local_date": "2020-09-01",
      "local_time": "18:00",
      "updated": 1597749113000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26389892,
        "name": "Königsplatz",
        "lat": 48.14606475830078,
        "lon": 11.564334869384766,
        "repinned": false,
        "address_1": "Königsplatz 1",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "is_online_event": false,
      "group": {
        "created": 1597153092000,
        "name": "Munich Labyrynsel",
        "id": 34082878,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munich-Labyrynsel",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munich-Labyrynsel/events/hmdpwrybcmbcb/",
      "description": "<p>We go, meditate together and take our time.<br/><a href=\"https://youtu.be/_IFvablc6EI\" class=\"embedded\">https://youtu.be/_IFvablc6EI</a></p> <p>When we have found a place, I will show you how a massage can be given and what you can consider.</p> <p>More information on this under",
      "visibility": "public",
      "member_pay_fee": false
    }
  ]

};

export { mockEvents };